version: "3.7"
services:
  app:
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123
    build: .
    ports:
      - "8585:8585"
    restart: always
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./initdata:/data/application